
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Wed Dec 03 14:18:33 CST 2025
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SHORT = 27;
  static final int SIGNED = 28;
  static final int TIMES = 42;
  static final int GT = 46;
  static final int ARROW = 73;
  static final int DIVASSIGN = 64;
  static final int CONST = 10;
  static final int BITNOT = 57;
  static final int GE = 48;
  static final int REGISTER = 25;
  static final int ENUM = 16;
  static final int RBRACK = 84;
  static final int SIZEOF = 29;
  static final int INTLIT = 3;
  static final int COMMA = 74;
  static final int RBRACE = 82;
  static final int RPAREN = 80;
  static final int LBRACK = 83;
  static final int LT = 45;
  static final int SUBASSIGN = 62;
  static final int DOUBLE = 14;
  static final int LBRACE = 81;
  static final int STRUCT = 31;
  static final int BWISEANDASSIGN = 66;
  static final int LPAREN = 79;
  static final int MODASSIGN = 65;
  static final int NOT = 53;
  static final int LE = 47;
  static final int DEC = 72;
  static final int VAR = 36;
  static final int FLOAT = 18;
  static final int GOTO = 21;
  static final int EQ = 49;
  static final int LSHIFTASSIGN = 69;
  static final int MOD = 44;
  static final int LONG = 24;
  static final int PLUS = 40;
  static final int DIVIDE = 43;
  static final int QUESTION = 78;
  static final int WHILE = 39;
  static final int UNION = 34;
  static final int ASSIGN = 60;
  static final int CHAR = 9;
  static final int ADDASSIGN = 61;
  static final int CHARLIT = 5;
  static final int SWITCH = 32;
  static final int DO = 13;
  static final int FOR = 19;
  static final int STRLIT = 4;
  static final int VOID = 37;
  static final int EXTERN = 17;
  static final int RETURN = 26;
  static final int BITOR = 55;
  static final int ELSE = 15;
  static final int BREAK = 7;
  static final int FUN = 20;
  static final int DOT = 77;
  static final int INT = 23;
  static final int SEMICOLON = 75;
  static final int EOF = 0;
  static final int DEFAULT = 12;
  static final int MULASSIGN = 63;
  static final int INC = 71;
  static final int MINUS = 41;
  static final int BITAND = 54;
  static final int OR = 52;
  static final int error = 1;
  static final int CONTINUE = 11;
  static final int IF = 22;
  static final int BITXOR = 56;
  static final int UNSIGNED = 35;
  static final int ID = 2;
  static final int COLON = 76;
  static final int BWISEORASSIGN = 67;
  static final int RSHIFTASSIGN = 70;
  static final int VOLATILE = 38;
  static final int CASE = 8;
  static final int RSHIFT = 59;
  static final int BWISEXORASSIGN = 68;
  static final int NEQ = 50;
  static final int AND = 51;
  static final int STATIC = 30;
  static final int LSHIFT = 58;
  static final int TYPEDEF = 33;
  static final int AUTO = 6;
}

